name: introvertedmarketer
favicon: null
layout_spectrum: 0.8542562865186483
typography_spectrum: 0.6847389291506261
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.45856919093057513
  lightness: 0.4053482913877815
  saturation: 0.8046794733963907
  rhythmicContrast: 0.888880196493119
purpose: []
